// Generated by IcedCoffeeScript 1.8.0-a
(function() {
  Creator;
  -Kruy(Vanna);

  Mentor;

  -Masahiro(Tanaka);

  -Hiroshi(Shikata);

  Logo(Designer);

  -Mao(Takahashi);

  Project(Name);

  -Khourn(Khemry);

  this.idealhack;

  this.dzeims;

  this.ataruohto0121;

  this.marqu3z;

  this.roboncode;

}).call(this);
