// Generated by IcedCoffeeScript 1.8.0-a
(function() {
  var ItemSchema, mongoose;

  mongoose = require('mongoose');

  ItemSchema = mongoose.Schema({
    id: {
      type: Number,
      index: {
        unique: true,
        sparse: true
      }
    },
    title: String,
    items: [
      {
        title: String,
        id: Number,
        pageType: String
      }
    ],
    content: String
  });

  module.exports.items = mongoose.model('Item', ItemSchema);

}).call(this);
