// Generated by IcedCoffeeScript 1.8.0-a
(function() {
  var app;

  app = angular.module('fmCases', ['onsen']);

  app.controller('AppCtrl', [
    '$scope', function($scope) {
      var getItems, getTitle;
      getTitle = function(id) {
        return 'title' + id;
      };
      getItems = function(navid) {
        return [
          {
            text: "item 1",
            navid: 1
          }, {
            text: "item 2",
            navid: 2
          }, {
            text: "item 3",
            navid: 3
          }, {
            text: "item 4",
            navid: 4
          }, {
            text: "item 5",
            navid: 5
          }, {
            text: "item 6",
            navid: 6
          }, {
            text: "item 7",
            navid: 7
          }, {
            text: "item 8",
            navid: 8
          }, {
            text: "item 9",
            navid: 9
          }
        ];
      };
      $scope.pageOpt = function() {
        return navi.getCurrentPage().options;
      };
      return $scope.pushPage = function(navid) {
        var options;
        options = {
          title: getTitle(navid),
          items: getItems(navid)
        };
        return navi.pushPage('views/navigation.html', options);
      };
    }
  ]);

}).call(this);
