// Generated by IcedCoffeeScript 1.8.0-a
(function() {
  var app,
    __slice = [].slice;

  window.iced = {
    Deferrals: (function() {
      function _Class(_arg) {
        this.continuation = _arg;
        this.count = 1;
        this.ret = null;
      }

      _Class.prototype._fulfill = function() {
        if (!--this.count) {
          return this.continuation(this.ret);
        }
      };

      _Class.prototype.defer = function(defer_params) {
        ++this.count;
        return (function(_this) {
          return function() {
            var inner_params, _ref;
            inner_params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            if (defer_params != null) {
              if ((_ref = defer_params.assign_fn) != null) {
                _ref.apply(null, inner_params);
              }
            }
            return _this._fulfill();
          };
        })(this);
      };

      return _Class;

    })(),
    findDeferral: function() {
      return null;
    },
    trampoline: function(_fn) {
      return _fn();
    }
  };
  window.__iced_k = window.__iced_k_noop = function() {};

  app = angular.module('fmCases', ['onsen']);

  app.controller('AppCtrl', [
    '$scope', '$http', function($scope, $http) {
      var getData, pageMap, serviceMap;
      pageMap = {
        'nav': 'views/navigation.html',
        'content': 'views/content.html'
      };
      serviceMap = {
        'nav': '/navigation/',
        'content': '/content/'
      };
      getData = function(item, cb) {
        var data, ___iced_passed_deferral, __iced_deferrals, __iced_k;
        __iced_k = __iced_k_noop;
        ___iced_passed_deferral = iced.findDeferral(arguments);
        (function(_this) {
          return (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "/opt/fmcases/app/js/app.coffee"
            });
            $http.get(serviceMap[item.pageType] + ("" + item.id)).success(__iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  return data = arguments[0];
                };
              })(),
              lineno: 16
            }));
            __iced_deferrals._fulfill();
          });
        })(this)((function(_this) {
          return function() {
            return cb(data);
          };
        })(this));
      };
      $scope.pageOpt = function() {
        return navi.getCurrentPage().options;
      };
      $scope.pushPage = function(item) {
        var data, ___iced_passed_deferral, __iced_deferrals, __iced_k;
        __iced_k = __iced_k_noop;
        ___iced_passed_deferral = iced.findDeferral(arguments);
        (function(_this) {
          return (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "/opt/fmcases/app/js/app.coffee",
              funcname: "pushPage"
            });
            getData(item, __iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  return data = arguments[0];
                };
              })(),
              lineno: 26
            }));
            __iced_deferrals._fulfill();
          });
        })(this)((function(_this) {
          return function() {
            return navi.pushPage(pageMap[item.pageType], data);
          };
        })(this));
      };
      return $scope.pushRoot = function() {
        return $scope.pushPage({
          id: 1,
          pageType: 'nav'
        });
      };
    }
  ]);

}).call(this);
