// Generated by IcedCoffeeScript 1.8.0-a
(function() {
  var app;

  app = angular.module('fmCases', ['onsen']);

  app.controller('AppCtrl', [
    '$scope', function($scope) {
      $scope.pageTitle = 'Page';
      return $scope.data = [
        {
          text: "item 1",
          modifier: "tappable"
        }, {
          text: "item 2",
          modifier: "tappable"
        }, {
          text: "item 3",
          modifier: "tappable"
        }, {
          text: "item 4",
          modifier: "tappable"
        }, {
          text: "item 5",
          modifier: "tappable"
        }, {
          text: "item 6",
          modifier: "tappable"
        }, {
          text: "item 7",
          modifier: "tappable"
        }, {
          text: "item 8",
          modifier: "tappable"
        }, {
          text: "item 9",
          modifier: "tappable"
        }
      ];
    }
  ]);

}).call(this);
